
package soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SpotService", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SpotService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateSpotFree", targetNamespace = "http://soap/", className = "soap.UpdateSpotFree")
    @ResponseWrapper(localName = "updateSpotFreeResponse", targetNamespace = "http://soap/", className = "soap.UpdateSpotFreeResponse")
    public void updateSpotFree(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateSpotOccupied", targetNamespace = "http://soap/", className = "soap.UpdateSpotOccupied")
    @ResponseWrapper(localName = "updateSpotOccupiedResponse", targetNamespace = "http://soap/", className = "soap.UpdateSpotOccupiedResponse")
    public void updateSpotOccupied(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
