
package soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SpotServiceService", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:8080/MainSystemImpl-1.0/SpotService?wsdl")
public class SpotServiceService
    extends Service
{

    private final static URL SPOTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SPOTSERVICESERVICE_EXCEPTION;
    private final static QName SPOTSERVICESERVICE_QNAME = new QName("http://soap/", "SpotServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/MainSystemImpl-1.0/SpotService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SPOTSERVICESERVICE_WSDL_LOCATION = url;
        SPOTSERVICESERVICE_EXCEPTION = e;
    }

    public SpotServiceService() {
        super(__getWsdlLocation(), SPOTSERVICESERVICE_QNAME);
    }

    public SpotServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SPOTSERVICESERVICE_QNAME, features);
    }

    public SpotServiceService(URL wsdlLocation) {
        super(wsdlLocation, SPOTSERVICESERVICE_QNAME);
    }

    public SpotServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SPOTSERVICESERVICE_QNAME, features);
    }

    public SpotServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpotServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SpotService
     */
    @WebEndpoint(name = "SpotServicePort")
    public SpotService getSpotServicePort() {
        return super.getPort(new QName("http://soap/", "SpotServicePort"), SpotService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpotService
     */
    @WebEndpoint(name = "SpotServicePort")
    public SpotService getSpotServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "SpotServicePort"), SpotService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPOTSERVICESERVICE_EXCEPTION!= null) {
            throw SPOTSERVICESERVICE_EXCEPTION;
        }
        return SPOTSERVICESERVICE_WSDL_LOCATION;
    }

}
